### ISSUE TITLE
Issue with output format

### ISSUE THREAD

**Issue by overthink** [hasanzk/Product-Listings-Matching#1]
Hi Hasan,

I was trying to evaluate your solution but there is a problem with the output format. Please make sure each line in the output file is a Result object as described on http://sortable.com/challenge/, i.e.

```
{
  "product_name": String
  "listings": Array[Listing]
}

```

An example line in the output file should look like:

```
{"listings": [{"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Red)"}, {"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio Exilim EX-FC150 10.1MP High Speed Digital Camera with 5x Optical Zoom, CMOS Shift Image Stabilization & 2.7-inch LCD (Red)"}, {"currency": "USD", "price": "249.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Black)"}], "product_name": "Casio_Exilim_EX-FC150"}
```

In your output the listings are not valid JSON (no commas between items), and also they appear to be arrays instead of the required JSON objects. e.g.

```
{"product_name": "Samsung TL220","listings":[["Samsung DualView TL220 - Appareil Photo NumÃ©rique Compact, 12,2 mÃ©gapixels - Rouge", "Samsung", "EUR", "290.00"]["Samsung DualView TL220 - Appareil Photo NumÃ©rique Compact, 12, 2 mÃ©gapixels - Bleu", "Samsung", "EUR", "290.00"]]}
```

If you are able to fix this up I'd be happy to take another look at your submission.

Thanks!

Mark (from sortable.com)

**Comment by hasanzk** [comment]
Issue has been fixed.

**Comment by overthink** [comment]
Hi Hasan.

Still having a problem.  The values for `product_name` in your output need to match exactly the `product_name` values found in products.txt.

e.g. from your output:
`{"listings":[ ... ], "product_name": "Sony Cyber-shot DSC-W310"}`

From products.txt the value of product_name for this camera should be `Sony_Cyber-shot_DSC-W310` (note the underscores).

**Comment by hasanzk** [comment]
This issue is also fixed now.
